<?php

$dictionary['DashboardBackups'] = array(
   'table' => 'dashboardbackups',
   'audited' => false,
   'inline_edit' => false,
   'duplicate_merge' => false,
   'fields' => array(
      'encoded_pages' =>
      array(
         'required' => false,
         'name' => 'encoded_pages',
         'vname' => 'LBL_ENCODED_PAGES',
         'type' => 'text',
         'massupdate' => 0,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => false,
         'reportable' => false,
         'unified_search' => false,
         'calculated' => false,
         'size' => '20',
         'studio' => 'visible',
         'rows' => '4',
         'cols' => '20',
      ),
      'encoded_dashlets' =>
      array(
         'required' => false,
         'name' => 'encoded_dashlets',
         'vname' => 'LBL_ENCODED_DASHLETS',
         'type' => 'text',
         'dbType' => 'mediumtext',
         'massupdate' => 0,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => false,
         'reportable' => true,
         'unified_search' => false,
         'calculated' => false,
         'size' => '20',
         'studio' => 'visible',
         'rows' => '4',
         'cols' => '20',
      ),
      "dashboardmanager" => array(
         'name' => 'dashboardmanager',
         'type' => 'link',
         'relationship' => 'dashboardbackups_dashboardmanager',
         'source' => 'non-db',
         'module' => 'DashboardManager',
         'bean_name' => false,
         'vname' => 'LBL_DASHBOARDMANAGER',
      ),
      "dashboardmanager_name" => array(
         'id_name' => 'dashboardmanager_id',
         'name' => 'dashboardmanager_name',
         'type' => 'relate',
         'source' => 'non-db',
         'vname' => 'LBL_DASHBOARDMANAGER_NAME',
         'link' => 'dashboardmanager',
         'table' => 'dashboardmanager',
         'module' => 'DashboardManager',
         'rname' => 'name',
      ),
      "dashboardmanager_id" => array(
         'name' => 'dashboardmanager_id',
         'type' => 'id',
         'vname' => 'LBL_DASHBOARDMANAGER_ID',
         'link' => 'dashboardmanager',
         'table' => 'dashboardmanager',
         'module' => 'DashboardManager',
         'rname' => 'id',
         'reportable' => false,
         'massupdate' => false,
         'duplicate_merge' => 'disabled',
         'hideacl' => true,
      ),
      "dashboardhistory" => array(
         'name' => 'dashboardhistory',
         'type' => 'link',
         'relationship' => 'dashboardbackups_dashboardhistory',
         'source' => 'non-db',
         'module' => 'DashboardHistory',
         'bean_name' => false,
         'vname' => 'LBL_DASHBOARDHISTORY',
      ),
      "dashboardhistory_name" => array(
         'id_name' => 'dashboardhistory_id',
         'name' => 'dashboardhistory_name',
         'type' => 'relate',
         'source' => 'non-db',
         'vname' => 'LBL_DASHBOARDHISTORY_NAME',
         'link' => 'dashboardhistory',
         'table' => 'dashboardhistory',
         'module' => 'DashboardHistory',
         'rname' => 'name',
      ),
      "dashboardhistory_id" => array(
         'name' => 'dashboardhistory_id',
         'type' => 'id',
         'vname' => 'LBL_DASHBOARDHISTORY_ID',
         'link' => 'dashboardhistory',
         'table' => 'dashboardhistory',
         'module' => 'DashboardHistory',
         'rname' => 'id',
         'reportable' => false,
         'massupdate' => false,
         'duplicate_merge' => 'disabled',
         'hideacl' => true,
      ),
   ),
   'relationships' => array(
   ),
   'optimistic_locking' => true,
   'unified_search' => false,
);
if ( !class_exists('VardefManager') ) {
   require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('DashboardBackups', 'DashboardBackups', array( 'basic', 'assignable' ));
