<?php

use MintHCM\Install\InstallController;
use MintHCM\Api\Middlewares\Params\ParamTypes\StringType;

$routes = array(
    "license" => array(
        "method" => "GET",
        "path" => "/install/license",
        "class" => InstallController::class,
        "function" => 'getLicense',
        "desc" => "Get the MintHCM license",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(),
    ),
    "environment" => array(
        "method" => "GET",
        "path" => "/install/environment",
        "class" => InstallController::class,
        "function" => 'verifyEnvironment',
        "desc" => "Verify the environment before installing",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(),
    ),
    "check_available_db_connection" => array(
        "method" => "GET",
        "path" => "/install/check_available_db_connection",
        "class" => InstallController::class,
        "function" => 'checkAvailableDBConnection',
        "desc" => "List available DB connections",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(),
    ),
    "validate_db_connection" => array(
        "method" => "POST",
        "path" => "/install/validate_db_connection",
        "class" => InstallController::class,
        "function" => 'validateDBConnection',
        "desc" => "Validate whether the DB connection returns an error",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(
            "databaseHost" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Url of db host',
                "example" => 'localhost',
            ),
            "databasePort" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'port of host',
                "example" => '3303',
            ),
            "databaseUsername" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Username for DB',
                "example" => 'root',
            ),
            "databasePassword" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Password for DB User',
                "example" => 'password!@#',
            ),
            "databaseName" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Name of the database to create',
                "example" => 'mintHCM',
            ),
        ),
    ),
    "save_db_connection" => array(
        "method" => "POST",
        "path" => "/install/save_db_connection",
        "class" => InstallController::class,
        "function" => 'saveDBConnection',
        "desc" => "Save the connection with the DB",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(
            "databaseHost" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Url of db host',
                "example" => 'localhost',
            ),
            "databasePort" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'port of host',
                "example" => '3303',
            ),
            "databaseUsername" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Username for DB',
                "example" => 'root',
            ),
            "databasePassword" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Password for DB User',
                "example" => 'password!@#',
            ),
            "databaseName" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Name of the database to create',
                "example" => 'mintHCM',
            ),
            "databaseCollation" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Database collation',
                "example" => 'utf8mb4_general_ci'
            ),
        ),
    ),
    "validate_es_connection" => array(
        "method" => "POST",
        "path" => "/install/validate_es_connection",
        "class" => InstallController::class,
        "function" => 'validateESConnection',
        "desc" => "Validate whether the ES conneciton returns an error",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(
            "elasticUser" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Username for the ElasticSearch user, can be empty',
                "example" => 'admin',
            ),
            "elasticPass" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Password for the ElasticSearch user, can be empty',
                "example" => 'password!@#',
            ),
            "elasticHost" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Host for the ElasticSearch',
                "example" => 'localhost',
            ),
            "elasticPort" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Port for the ElasticSearch',
                "example" => '9200',
            ),
        ),
    ),
    "save_es_connection" => array(
        "method" => "POST",
        "path" => "/install/save_es_connection",
        "class" => InstallController::class,
        "function" => 'saveESConnection',
        "desc" => "Save the connection with ES",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(
            "elasticUser" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Username for the ElasticSearch user, can be empty',
                "example" => 'admin',
            ),
            "elasticPass" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Password for the ElasticSearch user, can be empty',
                "example" => 'password!@#',
            ),
            "elasticHost" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Host for the ElasticSearch',
                "example" => 'localhost',
            ),
            "elasticPort" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Port for the ElasticSearch',
                "example" => '9200',
            ),
        ),
    ),
    "save_settings" => array(
        "method" => "POST",
        "path" => "/install/save_settings",
        "class" => InstallController::class,
        "function" => 'saveSettings',
        "desc" => "Save user settings, like admin credentials",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(
            "demoData" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Should you install demoData? Options are "yes" or "no"',
                "example" => 'yes',
            ),
            "systemAdminName" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Username for the system administrator',
                "example" => 'admin',
            ),
            "systemAdminPassword" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'Password for the system administrator',
                "example" => 'password!@#',
            ),
            "siteUrl" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'url for the site',
                "example" => 'https://site.net/MINT',
            ),
            "rootDirectory" => array(
                "type" => StringType::class,
                "required" => true,
                "desc" => 'root directory of your MintHCM install',
                "example" => '/var/www',
            ),
        ),
    ),
    "get_installation_steps_amount" => array(
        "method" => "GET",
        "path" => "/install/get_installation_steps_amount",
        "class" => InstallController::class,
        "function" => 'getInstallationStepsAmount',
        "desc" => "Returns the installation steps amount",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(),  
    ),
    "install" => array(
        "method" => "POST",
        "path" => "/install/install",
        "class" => InstallController::class,
        "function" => 'Installs the system, perform only after youve done the previous ones',
        "desc" => "Install",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(),
    ),
    "get_installation_progress" => array(
        "method" => "GET",
        "path" => "/install/get_installation_progress",
        "class" => InstallController::class,
        "function" => 'getInstallationProgress',
        "desc" => "Return current installation progress",
        "options" => array('auth' => false),
        "pathParams" => array(),
        "queryParams" => array(),
        "bodyParams" => array(),
    ),
);
