<?php
$dictionary['Certificates'] = array(
    'table' => 'certificates',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'start_date' => array(
            'name' => 'start_date',
            'label' => 'LBL_START_DATE',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'audited' => false,
            'mass_update' => false,
            'duplicate_merge' => '1',
            'reportable' => true,
            'importable' => true,
            'options' => 'date_range_search_dom',
            'enable_range_search' => '1',
            'validation' => array('type' => 'isbefore', 'compareto' => 'end_date'),
        ),
        'end_date' => array(
            'name' => 'end_date',
            'label' => 'LBL_END_DATE',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'audited' => false,
            'mass_update' => false,
            'duplicate_merge' => '1',
            'reportable' => true,
            'importable' => true,
            'options' => 'date_range_search_dom',
            'enable_range_search' => '1',
        ),
        'status' => array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'audited' => true,
            'default' => 'Active',
            'no_default' => false,
            'massupdate' => true,
            'importable' => false,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'certificates_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'documents' => array(
            'name' => 'documents',
            'type' => 'link',
            'relationship' => 'documents_certificates',
            'source' => 'non-db',
            'vname' => 'LBL_DOCUMENTS',
        ),
        "trainings" => array(
            'name' => 'trainings',
            'type' => 'link',
            'relationship' => 'certificates_trainings',
            'source' => 'non-db',
            'module' => 'Trainings',
            'bean_name' => 'Trainings',
            'vname' => 'LBL_RELATIONSHIP_CERTIFICATES_NAME',
        ),
        "candidate" => array(
            'name' => 'candidate',
            'type' => 'link',
            'relationship' => 'candidates_certificates',
            'source' => 'non-db',
            'module' => 'Candidates',
            'bean_name' => 'Candidates',
            'vname' => 'LBL_RELATIONSHIP_CANDIDATE_NAME',
            'id_name' => 'candidate_id',
        ),
        "candidate_name" => array(
            'name' => 'candidate_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_RELATIONSHIP_CANDIDATE_NAME',
            'id_name' => 'candidate_id',
            'link' => 'candidate',
            'module' => 'Candidates',
            'table' => 'candidates',
            'rname' => 'name',
            'audited' => true,
            'importable' => true,
            'required' => false,
            'reportable' => true,
            'massupdate' => false,
            'duplicate_merge' => 'enabled',
        ),
        "candidate_id" => array(
            'name' => 'candidate_id',
            'relationship' => 'candidates_certificates',
            'type' => 'id',
            'vname' => 'LBL_RELATIONSHIP_CANDIDATE_ID',
            'audited' => true,
            'reportable' => true,
        ),
    ),
    'relationships' => array(
        "candidates_certificates" => array(
            'lhs_module' => 'Candidates',
            'lhs_table' => 'candidates',
            'lhs_key' => 'id',
            'rhs_module' => 'Certificates',
            'rhs_table' => 'certificates',
            'rhs_key' => 'candidate_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('Certificates', 'Certificates',
    array('basic', 'assignable', 'security_groups', 'employee_related'));
