stages:
    - deploy
    - notification

AutoDeploy:
  image: registry.evolpe.net/evolpe/cicd-ssh:latest
  stage: deploy
  tags:
    - docker
  only:
    - mobile
  before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - ssh -p2574 root@10.8.0.134 "hostname && bash /var/www/mint4_mobile/scripts/updateMint4_token.sh mint4_mobile mobile && cd /var/www/mint4_mobile/legacy; sudo -u www-data php rebuildAndRepair.php"
  variables:
    GIT_STRATEGY: none

Success Notification:
  stage: notification
  image: alpine/curl
  tags:
    - docker
  script:
    - "curl -X POST -H 'Content-Type: application/json' --data '{\"text\":\":tak: Poprawny auto deploy dla brancha *'$CI_COMMIT_BRANCH'*\\nPipeline: '$CI_PIPELINE_URL'\"}' https://chat.evolpe.it/hooks/648af321d5a3b64cbf2842cd/ePW2g7qwYajnJjHADjkWb8aPbS69CkdWPSnyhcsysw4otSoH"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "mobile"'
      when: on_success
  variables:
    GIT_STRATEGY: none

Failure Notification:
  stage: notification
  image: alpine/curl
  tags:
    - docker
  script:
    - "curl -X POST -H 'Content-Type: application/json' --data '{\"text\":\":nie: :hellmo: Coś poszło nie tak w pipeline dla brancha *'$CI_COMMIT_BRANCH'*\\nPipeline: '$CI_PIPELINE_URL'\"}' https://chat.evolpe.it/hooks/648af321d5a3b64cbf2842cd/ePW2g7qwYajnJjHADjkWb8aPbS69CkdWPSnyhcsysw4otSoH"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "mobile"'
      when: on_failure
  variables:
    GIT_STRATEGY: none