stages:
    - deploy
    - notification

AutoDeploy:
  image: registry.evolpe.net/evolpe/cicd-ssh:latest
  stage: deploy
  tags:
    - docker
  only:
    - mint4_php8
  before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - ssh -p2271 root@10.8.0.134 "hostname && bash /var/www/develop/scripts/updateMint4.sh develop mint4_php8 && cd /var/www/develop/legacy; sudo -u www-data php rebuildAndRepair.php"

Success Notification:
  stage: notification
  image: alpine/curl
  tags:
    - docker
  script:
    - "curl -X POST -H 'Content-Type: application/json' --data '{\"text\":\":tak: Poprawny auto deploy dla brancha *'$CI_COMMIT_BRANCH'*\\nPipeline: '$CI_PIPELINE_URL'\"}' https://chat.evolpe.it/hooks/648af321d5a3b64cbf2842cd/ePW2g7qwYajnJjHADjkWb8aPbS69CkdWPSnyhcsysw4otSoH"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "mint4_php8"'
      when: on_success

Failure Notification:
  stage: notification
  image: alpine/curl
  tags:
    - docker
  script:
    - "curl -X POST -H 'Content-Type: application/json' --data '{\"text\":\":nie: :hellmo: Coś poszło nie tak w pipeline dla brancha *'$CI_COMMIT_BRANCH'*\\nPipeline: '$CI_PIPELINE_URL'\"}' https://chat.evolpe.it/hooks/648af321d5a3b64cbf2842cd/ePW2g7qwYajnJjHADjkWb8aPbS69CkdWPSnyhcsysw4otSoH"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "mint4_php8"'
      when: on_failure
