# Required metadata
sonar.projectKey=MINTHCM
sonar.projectName=MINTHCM
sonar.projectVersion=1.1

# Comma-separated paths to directories with sources (required)
sonar.sources=.
sonar.exclusions=MintHCM/vendor/**,MintHCM/k/**,MintHCM/lib/**,MintHCM/include/SugarXHprof/**,MintHCM/include/PHPExcel-1.8/**,MintHCM/inclde /nusoap/**,MintHCM/include/fonts/**,MintHCM/include/HTMLPurifier/**,MintHCM/include/HTTP_WebDAV_Server/**,MintHCM/include/javascript/c3/**,MintHCM/include/javascript/jquery/**,MintHCM/include/javascript/jstree/**,MintHCM/include/javascript/mozaik/**,MintHCM/include/javascript/phpjs/**,MintHCM/include/javascript/pivottable/**,MintHCM/include/javascript/qtip/**,MintHCM/include/javascript/tiny_mce/**,MintHCM/include/javascript/touchPunch/**,MintHCM/include/javascript/yui/**,MintHCM/include/javascript/yui3/**,MintHCM/include/language/**,MintHCM/include/pclzip/**,MintHCM/include/Pear/**,MintHCM/include/tcpdf/**,MintHCM/include/SuiteGraphs/rgraph/**,MintHCM/include/ytree/**,MintHCM/install/demoData.en_us.php/**,MintHCM/jssource/**,MintHCM/Zend/**,MintHCM/**/*en_us.lang.php

# Language
#sonar.language=php

# Encoding of the source files
sonar.sourceEncoding=UTF-8