# Required metadata
sonar.projectKey=MINTHCM
sonar.projectName=MINTHCM
sonar.projectVersion=1.0

# Comma-separated paths to directories with sources (required)
sonar.sources=**
sonar.exclusions=vendor/**,k/**,lib/**,include/SugarXHprof/**,include/PHPExcel-1.8/**,inclde /nusoap/**,include/fonts/**,include/HTMLPurifier/**,include/HTTP_WebDAV_Server/**,include/javascript/c3/**,include/javascript/jquery/**,include/javascript/jstree/**,include/javascript/mozaik/**,include/javascript/phpjs/**,include/javascript/pivottable/**,include/javascript/qtip/**,include/javascript/tiny_mce/**,include/javascript/touchPunch/**,include/javascript/yui/**,include/javascript/yui3/**,include/language/**,include/pclzip/**,include/Pear/**,include/tcpdf/**,include/SuiteGraphs/rgraph/**,include/ytree/**,install/demoData.en_us.php/**,jssource/**,Zend/**,**/*en_us.lang.php

# Language
#sonar.language=php

# Encoding of the source files
sonar.sourceEncoding=UTF-8