# Required metadata
sonar.projectKey=MintHCM
sonar.projectName=MintHCM
sonar.projectVersion=1.1

# Comma-separated paths to directories with sources (required)
sonar.sources=.
sonar.exclusions=legacy/vendor/**,legacy/k/**,legacy/lib/**,legacy/include/SugarXHprof/**,legacy/include/PHPExcel-1.8/**,legacy/inclde /nusoap/**,legacy/include/fonts/**,legacy/include/HTMLPurifier/**,legacy/include/HTTP_WebDAV_Server/**,legacy/include/javascript/c3/**,legacy/include/javascript/jquery/**,legacy/include/javascript/jstree/**,legacy/include/javascript/mozaik/**,legacy/include/javascript/phpjs/**,legacy/include/javascript/pivottable/**,legacy/include/javascript/qtip/**,legacy/include/javascript/tiny_mce/**,legacy/include/javascript/touchPunch/**,legacy/include/javascript/yui/**,legacy/include/javascript/yui3/**,legacy/include/language/**,legacy/include/pclzip/**,legacy/include/Pear/**,legacy/include/tcpdf/**,legacy/include/SuiteGraphs/rgraph/**,legacy/include/ytree/**,legacy/install/demoData.en_us.php/**,legacy/jssource/**,legacy/Zend/**,legacy/**/*en_us.lang.php

# Language
#sonar.language=php

# Encoding of the source files
sonar.sourceEncoding=UTF-8