<?php

$dictionary['Resources'] = array(
   'table' => 'resources',
   'audited' => true,
   'inline_edit' => true,
   'duplicate_merge' => true,
   'fields' => array(
      'type' => array(
         'required' => true,
         'name' => 'type',
         'vname' => 'LBL_TYPE',
         'type' => 'enum',
         'massupdate' => '1',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'enabled',
         'duplicate_merge_dom_value' => '1',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => 100,
         'size' => '20',
         'options' => 'type_list',
         'studio' => 'visible',
         'dependency' => false,
      ),
      'name' => array(
         'name' => 'name',
         'vname' => 'LBL_NAME',
         'type' => 'name',
         'link' => true,
         'dbType' => 'varchar',
         'len' => '255',
         'unified_search' => false,
         'full_text_search' => array(
            'boost' => 3,
         ),
         'required' => true,
         'importable' => 'required',
         'duplicate_merge' => 'enabled',
         'merge_filter' => 'disabled',
         'massupdate' => 0,
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'duplicate_merge_dom_value' => '1',
         'audited' => true,
         'inline_edit' => true,
         'reportable' => true,
         'size' => '20',
      ),
      'unavailable' => array(
         'required' => false,
         'name' => 'unavailable',
         'vname' => 'LBL_UNAVAILABLE',
         'type' => 'bool',
         'massupdate' => 0,
         'default' => '0',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'enabled',
         'duplicate_merge_dom_value' => '1',
         'audited' => true,
         'inline_edit' => true,
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => '255',
         'size' => '20',
      ),
      "reservations" => array(
         'name' => 'reservations',
         'type' => 'link',
         'relationship' => 'resources_reservations',
         'source' => 'non-db',
         'module' => 'Reservations',
         'bean_name' => 'Reservations',
         'side' => 'right',
         'vname' => 'LBL_RESERVATIONS',
      ),
      'meetings' => array(
         'name' => 'meetings',
         'type' => 'link',
         'relationship' => 'meetings_resources',
         'source' => 'non-db',
         'vname' => 'LBL_MEETINGS',
      ),
      'calls' => array(
         'name' => 'calls',
         'type' => 'link',
         'relationship' => 'calls_resources',
         'source' => 'non-db',
         'vname' => 'LBL_CALLS',
      ),
   ),
   'relationships' => array(),
   'optimistic_locking' => true,
   'unified_search' => true,
);
if ( !class_exists('VardefManager') ) {
   require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Resources', 'Resources', array('basic', 'assignable', 'security_groups', 'employee_related'));

$dictionary["Resources"]["fields"]['description']['audited'] = true;
