<?php

$dictionary['SalaryRange'] = array(
    'table' => 'salaryrange',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'start_date' => array(
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'label' => 'LBL_START_DATE',
            'type' => 'date',
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'end_date' => array(
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'label' => 'LBL_END_DATE',
            'type' => 'date',
            'importable' => 'true',
            'reportable' => true,
            'audited' => true,
        ),
        'gross_value_from' => array(
            'name' => 'gross_value_from',
            'vname' => 'LBL_GROSS_VALUE_FROM',
            'label' => 'LBL_GROSS_VALUE_FROM',
            'type' => 'currency',
            'dbType' => 'currency',
            'enable_range_search' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'convertToBase' => true,
            'showTransactionalAmount' => true,
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'gross_value_from_usdollar' => array(
            'name' => 'gross_value_from_usdollar',
            'vname' => 'LBL_GROSS_VALUE_FROM_USDOLLAR',
            'label' => 'LBL_GROSS_VALUE_FROM_USDOLLAR',
            'type' => 'currency',
            'group' => 'gross_value_from',
            'dbType' => 'currency',
            'disable_num_format' => true,
            'duplicate_merge' => 'disabled',
            'studio' => false,
            'readonly' => true,
            'is_base_currency' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'formula' => 'ifElse(isNumeric($gross_value_from), currencyDivide($gross_value_from, $base_rate), "")',
            'calculated' => true,
            'enforced' => true,
            'reportable' => false,
            'audited' => false,
            'importable' => false,
        ),
        'gross_value_to' => array(
            'name' => 'gross_value_to',
            'vname' => 'LBL_GROSS_VALUE_TO',
            'label' => 'LBL_GROSS_VALUE_TO',
            'type' => 'currency',
            'dbType' => 'currency',
            'enable_range_search' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'convertToBase' => true,
            'showTransactionalAmount' => true,
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'gross_value_to_usdollar' => array(
            'name' => 'gross_value_to_usdollar',
            'vname' => 'LBL_GROSS_VALUE_TO_USDOLLAR',
            'label' => 'LBL_GROSS_VALUE_TO_USDOLLAR',
            'type' => 'currency',
            'group' => 'gross_value_to',
            'dbType' => 'currency',
            'disable_num_format' => true,
            'duplicate_merge' => 'disabled',
            'studio' => false,
            'readonly' => true,
            'is_base_currency' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'formula' => 'ifElse(isNumeric($gross_value_to), currencyDivide($gross_value_to, $base_rate), "")',
            'calculated' => true,
            'enforced' => true,
            'reportable' => false,
            'audited' => false,
            'importable' => false,
        ),
        'currency_id' => array(
            'name' => 'currency_id',
            'dbType' => 'id',
            'vname' => 'LBL_CURRENCY_ID',
            'type' => 'currency_id',
            'function' => 'getCurrencies',
            'function_bean' => 'Currencies',
            'required' => false,
            'reportable' => false,
            'default' => '-99',
            'importable' => false,
        ),
        'net_value_from' => array(
            'name' => 'net_value_from',
            'vname' => 'LBL_NET_VALUE_FROM',
            'label' => 'LBL_NET_VALUE_FROM',
            'type' => 'currency',
            'dbType' => 'currency',
            'enable_range_search' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'convertToBase' => true,
            'showTransactionalAmount' => true,
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'net_value_from_usdollar' => array(
            'name' => 'net_value_from_usdollar',
            'vname' => 'LBL_NET_VALUE_FROM_USDOLLAR',
            'label' => 'LBL_NET_VALUE_FROM_USDOLLAR',
            'type' => 'currency',
            'group' => 'net_value_from',
            'dbType' => 'currency',
            'disable_num_format' => true,
            'duplicate_merge' => 'disabled',
            'studio' => false,
            'readonly' => true,
            'is_base_currency' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'formula' => 'ifElse(isNumeric($net_value_from), currencyDivide($net_value_from, $base_rate), "")',
            'calculated' => true,
            'enforced' => true,
            'reportable' => false,
            'audited' => false,
            'importable' => false,
        ),
        'net_value_to' => array(
            'name' => 'net_value_to',
            'vname' => 'LBL_NET_VALUE_TO',
            'label' => 'LBL_NET_VALUE_TO',
            'type' => 'currency',
            'dbType' => 'currency',
            'enable_range_search' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'convertToBase' => true,
            'showTransactionalAmount' => true,
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'net_value_to_usdollar' => array(
            'name' => 'net_value_to_usdollar',
            'vname' => 'LBL_NET_VALUE_TO_USDOLLAR',
            'label' => 'LBL_NET_VALUE_TO_USDOLLAR',
            'type' => 'currency',
            'group' => 'net_value_to',
            'dbType' => 'currency',
            'disable_num_format' => true,
            'duplicate_merge' => 'disabled',
            'studio' => false,
            'readonly' => true,
            'is_base_currency' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'formula' => 'ifElse(isNumeric($net_value_to), currencyDivide($net_value_to, $base_rate), "")',
            'calculated' => true,
            'enforced' => true,
            'reportable' => false,
            'audited' => false,
            'importable' => false,
        ),
        'employer_costs_from' => array(
            'name' => 'employer_costs_from',
            'vname' => 'LBL_EMPLOYER_COSTS_FROM',
            'label' => 'LBL_EMPLOYER_COSTS_FROM',
            'type' => 'currency',
            'dbType' => 'currency',
            'enable_range_search' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'convertToBase' => true,
            'showTransactionalAmount' => true,
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'employer_costs_from_usdollar' => array(
            'name' => 'employer_costs_from_usdollar',
            'vname' => 'LBL_EMPLOYER_COSTS_FROM_USDOLLAR',
            'label' => 'LBL_EMPLOYER_COSTS_FROM_USDOLLAR',
            'type' => 'currency',
            'group' => 'employer_costs_from',
            'dbType' => 'currency',
            'disable_num_format' => true,
            'duplicate_merge' => 'disabled',
            'studio' => false,
            'readonly' => true,
            'is_base_currency' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'formula' => 'ifElse(isNumeric($employer_costs_from), currencyDivide($employer_costs_from, $base_rate), "")',
            'calculated' => true,
            'enforced' => true,
            'reportable' => false,
            'audited' => false,
            'importable' => false,
        ),
        'employer_costs_to' => array(
            'name' => 'employer_costs_to',
            'vname' => 'LBL_EMPLOYER_COSTS_TO',
            'label' => 'LBL_EMPLOYER_COSTS_TO',
            'type' => 'currency',
            'dbType' => 'currency',
            'enable_range_search' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'convertToBase' => true,
            'showTransactionalAmount' => true,
            'required' => true,
            'importable' => 'required',
            'reportable' => true,
            'audited' => true,
        ),
        'employer_costs_to_usdollar' => array(
            'name' => 'employer_costs_to_usdollar',
            'vname' => 'LBL_EMPLOYER_COSTS_TO_USDOLLAR',
            'label' => 'LBL_EMPLOYER_COSTS_TO_USDOLLAR',
            'type' => 'currency',
            'group' => 'employer_costs_to',
            'dbType' => 'currency',
            'disable_num_format' => true,
            'duplicate_merge' => 'disabled',
            'studio' => false,
            'readonly' => true,
            'is_base_currency' => true,
            'related_fields' => array(
                'currency_id',
                'base_rate',
            ),
            'formula' => 'ifElse(isNumeric($employer_costs_to), currencyDivide($employer_costs_to, $base_rate), "")',
            'calculated' => true,
            'enforced' => true,
            'reportable' => false,
            'audited' => false,
            'importable' => false,
        ),
        'positions' => array(
            'name' => 'positions',
            'type' => 'link',
            'relationship' => 'position_salaryranges',
            'source' => 'non-db',
            'module' => 'Positions',
            'bean_name' => 'Positions',
            'vname' => 'LBL_POSITIONS',
            'label' => 'LBL_POSITIONS',
            'id_link' => 'position_id',
        ),
        'position_id' => array(
            'name' => 'position_id',
            'relationship' => 'position_salaryranges',
            'type' => 'id',
            'vname' => 'LBL_POSITION_ID',
            'label' => 'LBL_POSITION_ID',
            'audited' => true,
            'importable' => true,
            'reportable' => true,
        ),
        'position_name' => array(
            'name' => 'position_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_POSITION_NAME',
            'label' => 'LBL_POSITION_NAME',
            'id_name' => 'position_id',
            'link' => 'position',
            'module' => 'Positions',
            'table' => 'positions',
            'rname' => 'name',
            'importable' => true,
            'reportable' => true,
            'audited' => true,
            'required' => true,
        ),

    ),
    'relationships' => array(
        'position_salaryranges' => array(
            'lhs_module' => 'Positions',
            'lhs_table' => 'positions',
            'lhs_key' => 'id',
            'rhs_module' => 'SalaryRange',
            'rhs_table' => 'salaryrange',
            'rhs_key' => 'position_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('SalaryRange', 'SalaryRange', array('basic', 'assignable', 'taggable'));

$dictionary['SalaryRange']['fields']['name']['vt_readonly'] = true;
$dictionary['SalaryRange']['fields']['name']['audited'] = true;
$dictionary['SalaryRange']['fields']['name']['related_fields'] = array(
    'position_name',
    'start_date',
    'end_date',
);
$dictionary['SalaryRange']['fields']['name']['disable_num_format'] = 1;
