<?php
// Generated by the Entity Creator

/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * MintHCM is a Human Capital Management software based on SuiteCRM developed by MintHCM, 
 * Copyright (C) 2018-2025 MintHCM
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by SugarCRM" 
 * logo and "Supercharged by SuiteCRM" logo and "Reinvented by MintHCM" logo. 
 * If the display of the logos is not reasonably feasible for technical reasons, the 
 * Appropriate Legal Notices must display the words "Powered by SugarCRM" and 
 * "Supercharged by SuiteCRM" and "Reinvented by MintHCM".
 */

namespace MintHCM\Api\Entities;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;

/**
 * @ORM\Entity(repositoryClass="MintHCM\Api\Repositories\UsersRepository")
 * @ORM\Table(name="users", indexes={
 *   @ORM\Index(name="userspk", columns={"id"}), 
 *   @ORM\Index(name="idx_user_name", columns={"user_name", "is_group", "status", "last_name", "first_name", "id"})})
 */
class Employee
{
    /**
         * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
            * @ORM\Column(type="string", length="36")
            */
    public $id;

    /**
            * @ORM\Column(type="string", length="60")
            */
    public $user_name;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $user_hash;

    /**
            * @ORM\Column(type="boolean")
            */
    public $system_generated_password;

    /**
            * @ORM\Column(type="datetime")
            */
    public $pwd_last_changed;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $authenticate_id;

    /**
            * @ORM\Column(type="boolean")
            */
    public $sugar_login;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $first_name;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $last_name;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_indexed;

    /**
            * @ORM\Column(type="boolean")
            */
    public $is_admin;

    /**
            * @ORM\Column(type="boolean")
            */
    public $external_auth_only;

    /**
            * @ORM\Column(type="boolean")
            */
    public $receive_notifications;

    /**
            * @ORM\Column(type="text")
            */
    public $description;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_entered;

    /**
            * @ORM\Column(type="datetime")
            */
    public $date_modified;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $modified_user_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $created_by;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $title;

    /**
            * @ORM\Column(type="string", length="255")
            */
    public $photo;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $department;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $phone_home;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $phone_mobile;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $phone_work;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $phone_other;

    /**
            * @ORM\Column(type="string", length="50")
            */
    public $phone_fax;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $status;

    /**
            * @ORM\Column(type="string", length="150")
            */
    public $primary_address_street;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $primary_address_city;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $primary_address_state;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $primary_address_country;

    /**
            * @ORM\Column(type="string", length="20")
            */
    public $primary_address_postalcode;

    /**
            * @ORM\Column(type="boolean")
            */
    public $deleted;

    /**
            * @ORM\Column(type="boolean")
            */
    public $portal_only;

    /**
            * @ORM\Column(type="boolean")
            */
    public $show_on_employees;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $employee_status;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $messenger_id;

    /**
            * @ORM\Column(type="string", length="100")
            */
    public $messenger_type;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $reports_to_id;

    /**
            * @ORM\Column(type="string")
            */
    public $business_role;

    /**
            * @ORM\Column(type="boolean")
            */
    public $is_group;

    /**
            * @ORM\Column(type="boolean")
            */
    public $factor_auth;

    /**
            * @ORM\Column(type="string")
            */
    public $factor_auth_interface;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $position_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $forced_tabs_dashboard_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $locked_dashboard_id;

    /**
            * @ORM\Column(type="string", length="36")
            */
    public $one_time_default_dashboard_id;

    /**
            * @ORM\Column(type="date")
            */
    public $birthdate;

    /**
            * @ORM\Column(type="text")
            */
    public $app_tokens;


public function __construct()
{
    }
}