<?php

$popupMeta = array(
   'moduleMain' => 'Transportations',
   'varName' => 'Transportations',
   'orderBy' => 'transportations.name',
   'whereClauses' => array(
      'from_city' => 'transportations.from_city',
      'to_city' => 'transportations.to_city',
      'type' => 'transportations.type',
      'other_transportation' => 'transportations.other_transportation',
      'name' => 'transportations.name',
      'trans_date' => 'transportations.trans_date',
   ),
   'searchInputs' => array(
      'from_city',
      'to_city',
      'type',
      'other_transportation',
      'name',
      'trans_date',
   ),
   'searchdefs' => array(
      'name' => array(
         'type' => 'name',
         'label' => 'LBL_NAME',
         'width' => '10%',
         'name' => 'name',
      ),
      'from_city' => array(
         'type' => 'varchar',
         'label' => 'LBL_FROM_CITY',
         'width' => '10%',
         'name' => 'from_city',
      ),
      'to_city' => array(
         'type' => 'varchar',
         'label' => 'LBL_TO_CITY',
         'width' => '10%',
         'name' => 'to_city',
      ),
      'trans_date' => array(
         'type' => 'date',
         'label' => 'LBL_TRANS_DATE',
         'width' => '10%',
         'name' => 'trans_date',
      ),
      'type' => array(
         'type' => 'enum',
         'studio' => 'visible',
         'label' => 'LBL_TYPE',
         'sortable' => false,
         'width' => '10%',
         'name' => 'type',
      ),
      'other_transportation' => array(
         'type' => 'varchar',
         'label' => 'LBL_OTHER_TRANSPORTATION',
         'width' => '10%',
         'name' => 'other_transportation',
      ),
      'assigned_user_name' => array(
         'link' => 'assigned_user_link',
         'type' => 'relate',
         'label' => 'LBL_ASSIGNED_TO_NAME',
         'width' => '10%',
         'name' => 'assigned_user_name',
      ),
   ),
   'listviewdefs' => array(
      'NAME' => array(
         'type' => 'name',
         'label' => 'LBL_NAME',
         'width' => '10%',
         'default' => true,
         'name' => 'name',
         'link' => true,
      ),
      'FROM_CITY' => array(
         'type' => 'varchar',
         'label' => 'LBL_FROM_CITY',
         'width' => '10%',
         'default' => true,
         'name' => 'from_city',
      ),
      'TO_CITY' => array(
         'type' => 'varchar',
         'label' => 'LBL_TO_CITY',
         'width' => '10%',
         'default' => true,
         'name' => 'to_city',
      ),
      'TRANS_DATE' => array(
         'type' => 'date',
         'label' => 'LBL_TRANS_DATE',
         'width' => '10%',
         'default' => true,
      ),
      'TYPE' => array(
         'type' => 'enum',
         'default' => true,
         'studio' => 'visible',
         'label' => 'LBL_TYPE',
         'sortable' => true,
         'width' => '10%',
         'name' => 'type',
      ),
      'OTHER_TRANSPORTATION' => array(
         'type' => 'varchar',
         'label' => 'LBL_OTHER_TRANSPORTATION',
         'width' => '10%',
         'default' => true,
         'name' => 'other_transportation',
      ),
      'OTHER_INFO' => array(
         'type' => 'varchar',
         'label' => 'LBL_OTHER_INFO',
         'width' => '10%',
         'default' => true,
         'name' => 'other_info',
      ),
      'ASSIGNED_USER_NAME' => array(
         'link' => 'assigned_user_link',
         'type' => 'relate',
         'label' => 'LBL_ASSIGNED_TO_NAME',
         'width' => '10%',
         'default' => true,
         'name' => 'assigned_user_name',
      ),
   ),
);
