<?php

$module_name = 'Delegations';
$listViewDefs [$module_name] = array(
   'NAME' => array(
      'width' => '32%',
      'label' => 'LBL_NAME',
      'default' => true,
      'link' => true,
      'related_fields' => array( 'owner' ),
   ),   
   'ASSIGNED_USER_NAME' => array(
      'width' => '9%',
      'label' => 'LBL_ASSIGNED_TO_NAME',
      'module' => 'Employees',
      'id' => 'ASSIGNED_USER_ID',
      'default' => true,
   ),
   'OBTAINED_SUM' => array(
      'type' => 'currency',
      'label' => 'LBL_OBTAINED_SUM',
      'currency_format' => true,
      'width' => '18%',
      'default' => false,
   ),
   'OBTAINED_SUM_USDOLLARS' => array(
      'type' => 'currency',
      'label' => translate('LBL_OBTAINED_SUM', $module_name) . ' (' . $this->ss->_tpl_vars['CURRENCY_SYMBOL'] . ')',
      'currency_format' => true,
      'width' => '18%',
      'default' => true,
   ),
   'PURPOSE' => array(
      'type' => 'varchar',
      'default' => true,
      'label' => 'LBL_PURPOSE',
      'width' => '10%',
   ),
   'RETURN_SUM_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_RETURN_SUM',
      'currency_format' => true,
      'width' => '10%',
      'default' => true,
      'related_fields' => array(
         'regimen_value',
         'accommodation_value',
         'start_date',
         'end_date',
         'obtained_sum',
      ),
   ),
   'START_DATE' => array(
      'type' => 'datetimecombo',
      'label' => 'LBL_START_DATE',
      'width' => '10%',
      'default' => true,
   ),
   'END_DATE' => array(
      'type' => 'datetimecombo',
      'label' => 'LBL_END_DATE',
      'width' => '10%',
      'default' => true,
   ),
   'TOTAL_EXPENSES_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_TOTAL_EXPENSES',
      'related_fields' => array(
         'regimen_value',
         'accommodation_value',
         'start_date',
         'end_date',
      ),
      'currency_format' => true,
      'width' => '10%',
      'default' => true,
   ),
   'TRANSPORT_COST_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_TRANSPORT_COST',
      'currency_format' => true,
      'width' => '10%',
      'default' => false,
   ),
   'REGIMENTS_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_REGIMENTS',
      'related_fields' => array(
         'regimen_value',
         'start_date',
         'end_date',
      ),
      'currency_format' => true,
      'width' => '10%',
      'default' => false,
   ),
   'TOTAL_ACCOMMODATION_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_TOTAL_ACCOMMODATION',
      'currency_format' => true,
      'width' => '10%',
      'default' => false,
   ),
   'ACCOMMODATION_LUMP_SUM_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_ACCOMMODATION_LUMP_SUM',
      'currency_format' => true,
      'related_fields' => array(
         'accommodation_value',
         'start_date',
         'end_date',
      ),
      'width' => '10%',
      'default' => false,
   ),
   'OTHER_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_OTHER',
      'currency_format' => true,
      'width' => '10%',
      'default' => false,
   ),
   'OWNER' => array(
      'type' => 'bool',
      'label' => 'LBL_OWNER',
      'width' => '5%',
      'default' => false,
   ),
   'PAYOFF_SUM_USDOLLAR' => array(
      'type' => 'currency',
      'label' => 'LBL_PAYOFF_SUM',
      'currency_format' => true,
      'width' => '10%',
      'related_fields' => array(
         'regimen_value',
         'accommodation_value',
         'start_date',
         'end_date',
         'obtained_sum',
      ),
      'default' => false,
   ),
);
