<?php

$dictionary['OnboardingOffboardingElements'] = array(
   'table' => 'onboardingoffboardingelements',
   'audited' => true,
   'inline_edit' => true,
   'duplicate_merge' => true,
   'importable' => true,
   'fields' => array(
      'type' =>
      array(
         'required' => true,
         'name' => 'type',
         'vname' => 'LBL_TYPE',
         'type' => 'enum',
         'massupdate' => '1',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => 100,
         'size' => '20',
         'options' => 'onoff_elements_list',
         'studio' => 'visible',
         'dependency' => false,
      ),
      'task_duration' =>
      array(
         'required' => true,
         'name' => 'task_duration',
         'vname' => 'LBL_TASK_DURATION',
         'type' => 'float',
         'massupdate' => 0,
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => '18',
         'size' => '20',
         'precision' => '2',
         'enable_range_search' => true,
         'options' => 'numeric_range_search_dom',
         'disable_num_format' => '',
         'min' => 0,
         'max' => false,
         'validation' =>
         array(
            'type' => 'range',
            'min' => 0,
            'max' => false,
         ),
      ),
      'days_from_start' =>
      array(
         'required' => true,
         'name' => 'days_from_start',
         'vname' => 'LBL_DAYS_FROM_START',
         'type' => 'int',
         'massupdate' => 0,
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => '255',
         'size' => '20',
         'enable_range_search' => true,
         'options' => 'numeric_range_search_dom',
         'disable_num_format' => '',
         'min' => false,
         'max' => false,
      ),
      "users" => array(
         'name' => 'users',
         'type' => 'link',
         'relationship' => 'users_onboardingoffboardingelements',
         'source' => 'non-db',
         'module' => 'Users',
         'bean_name' => 'User',
         'vname' => 'LBL_USERS_ONBOARDINGOFFBOARDINGELEMENTS',
         'id_name' => 'user_id',
      ),
      "user_name" => array(
         'name' => 'user_name',
         'type' => 'relate',
         'source' => 'non-db',
         'vname' => 'LBL_USERS_NAME',
         'save' => true,
         'id_name' => 'user_id',
         'link' => 'users',
         'module' => 'Users',
         'table' => 'users',
         'rname' => 'name',
         'required' => true,
         'vt_dependency' => "not(equals(\$own_task,'1'))",
      ),
      "user_id" => array(
         'name' => 'user_id',
         'relationship' => 'users_onboardingoffboardingelements',
         'type' => 'id',
         'vname' => 'LBL_USERS_ID',
      ),
      'own_task' =>
      array(
         'required' => false,
         'name' => 'own_task',
         'vname' => 'LBL_OWN_TASK',
         'type' => 'bool',
         'massupdate' => 0,
         'default' => '0',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'enabled',
         'duplicate_merge_dom_value' => '1',
         'audited' => true,
         'inline_edit' => true,
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => '255',
         'size' => '20',
         'vt_dependency' => "equals(\$type,'task')"
      ),
      'onboardingtemplates' => array(
         'name' => 'onboardingtemplates',
         'type' => 'link',
         'relationship' => 'onboardingoffboardingelements_onboardingtemplates',
         'module' => 'OnboardingTemplates',
         'bean_name' => 'OnboardingTemplates',
         'source' => 'non-db',
         'vname' => 'LBL_ONBOARDINGTEMPLATES',
      ),
      'offboardingtemplates' => array(
         'name' => 'offboardingtemplates',
         'type' => 'link',
         'relationship' => 'onboardingoffboardingelements_offboardingtemplates',
         'module' => 'OffboardingTemplates',
         'bean_name' => 'OffboardingTemplates',
         'source' => 'non-db',
         'vname' => 'LBL_OFFBOARDINGTEMPLATES',
      ),
   ),
   'relationships' => array(
      "users_onboardingoffboardingelements" => array(
         'lhs_module' => 'Users',
         'lhs_table' => 'users',
         'lhs_key' => 'id',
         'rhs_module' => 'OnboardingOffboardingElements',
         'rhs_table' => 'onboardingoffboardingelements',
         'rhs_key' => 'user_id',
         'relationship_type' => 'one-to-many',
      ),
   ),
   'optimistic_locking' => true,
   'unified_search' => true,
);
if ( !class_exists('VardefManager') ) {
   require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('OnboardingOffboardingElements', 'OnboardingOffboardingElements',
        array(
           'basic',
           'assignable',
           'security_groups'
        )
);
