<?php

$dictionary['Goals'] = array(
   'table' => 'goals',
   'audited' => true,
   'inline_edit' => true,
   'duplicate_merge' => true,
   'fields' => array(
      'date_start' =>
      array(
         'required' => false,
         'name' => 'date_start',
         'vname' => 'LBL_DATE_START',
         'type' => 'datetimecombo',
         'massupdate' => '1',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'size' => '20',
         'enable_range_search' => true,
         'options' => 'date_range_search_dom',
         'dbType' => 'datetime',
         'validation' => array( 'type' => 'isbefore', 'compareto' => 'date_end' ),
      ),
      'date_end' =>
      array(
         'required' => false,
         'name' => 'date_end',
         'vname' => 'LBL_DATE_END',
         'type' => 'datetimecombo',
         'massupdate' => '1',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'size' => '20',
         'enable_range_search' => true,
         'options' => 'date_range_search_dom',
         'dbType' => 'datetime',
      ),
      'status' =>
      array(
         'required' => false,
         'name' => 'status',
         'vname' => 'LBL_STATUS',
         'type' => 'enum',
         'massupdate' => '1',
         'default' => 'planned',
         'no_default' => false,
         'comments' => '',
         'help' => '',
         'importable' => 'true',
         'duplicate_merge' => 'disabled',
         'duplicate_merge_dom_value' => '0',
         'audited' => true,
         'inline_edit' => '',
         'reportable' => true,
         'unified_search' => false,
         'merge_filter' => 'disabled',
         'len' => 100,
         'size' => '20',
         'options' => 'goals_status_list',
         'studio' => 'visible',
         'dependency' => false,
      ),
      'appraisalitems' => array(
         'name' => 'appraisalitems',
         'type' => 'link',
         'relationship' => 'appraisalitems_goals',
         'module' => 'AppraisalItems',
         'bean_name' => 'AppraisalItems', 
         'source' => 'non-db',
         'vname' => 'LBL_APPRAISALITEMS',
      ),
   ),
   'relationships' => array(
      'appraisalitems_goals' => array(
         'lhs_module' => 'Goals',
         'lhs_table' => 'goals',
         'lhs_key' => 'id',
         'rhs_module' => 'AppraisalItems',
         'rhs_table' => 'appraisalitems',
         'rhs_key' => 'parent_id',
         'relationship_type' => 'one-to-many',
         'relationship_role_column' => 'parent_type',
         'relationship_role_column_value' => 'Goals'
      ),
   ),
   'optimistic_locking' => true,
   'unified_search' => true,
);
if ( !class_exists('VardefManager') ) {
   require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Goals', 'Goals', array( 'basic', 'assignable', 'employee_related', 'security_groups' ));
